# EMCAPI

networking:

  # IP the API will listen on
  host: 127.0.0.1

  # Port the API will listen on
  port: 8080

  # The URL path, for instance https://example.com/v3/aurora where aurora is the string written below, version numbers are always present
  url_path: aurora

behaviour:

  filterable_endpoint:
    #The maximum amount of values the user can check for each filter field.
    max_expected_values: 100
    #The maximum amount of field filters the user can use per query.
    max_filters: 5
    #The maximum amount of objects returned in each response.
    page_size: 100

  # Setting for testing reasons
  developer_mode: false

  # Enable for v1 and v2 endpoints to be enabled
  enable_legacy_endpoints: true